"""add room_id to chat model

Revision ID: 208fd27469e4
Revises: 5e3686493d50
Create Date: 2023-11-17 14:40:18.685811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208fd27469e4'
down_revision = '5e3686493d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
