"""add admins relationsip to notifications

Revision ID: 242127c01100
Revises: 87a02154fa21
Create Date: 2024-02-04 15:24:05.420940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242127c01100'
down_revision = '87a02154fa21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
