"""add chat time to chats model

Revision ID: 59f7e35920ba
Revises: 208fd27469e4
Create Date: 2023-11-18 21:01:40.619117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f7e35920ba'
down_revision = '208fd27469e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_time_stamp', sa.String(), server_default='Sat Nov 9:11 2023', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('chat_time_stamp')

    # ### end Alembic commands ###
