"""add chat time stamp to chats

Revision ID: a6fb0b178700
Revises: 208fd27469e4
Create Date: 2023-11-18 22:14:11.158290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fb0b178700'
down_revision = '208fd27469e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_time_stamp', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('chat_time_stamp')

    # ### end Alembic commands ###
