"""add chat time stamp to chats

Revision ID: aba9b3db1c81
Revises: 208fd27469e4
Create Date: 2023-11-19 12:40:26.457460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba9b3db1c81'
down_revision = '208fd27469e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_time_stamp', sa.DateTime(), server_default='Sun 12:11 PM', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('chat_time_stamp')

    # ### end Alembic commands ###
