"""add sender type and id to messages

Revision ID: bb60e4480082
Revises: 56acacfa976d
Create Date: 2023-11-15 12:04:19.346819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb60e4480082'
down_revision = '56acacfa976d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('messages_author_fkey', type_='foreignkey')
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('messages_author_fkey', 'visitors', ['author'], ['id'])
        batch_op.drop_column('sender_id')
        batch_op.drop_column('sender_type')

    # ### end Alembic commands ###
